### ISSUE TITLE
Multispecies observations mass upload

### ISSUE THREAD

**Issue by creeas** [sharkipedia/sharkipedia#116]
Hey @coffeejunk we just did a large upload of trait data and noticed a bug in papers with multiple species. When this data is imported every measurement is assigned to the first species in the list. For example in the most recent trait upload source White2007b has info on multiple species but every trait has been assigned to Atelomycterus baliensis. This is an issue with species being treated as an observation level metric rather than measurement level. I know we had some discussions about this in the past. Is there a way to fix this for the mass uploads, or is the way forward to enter these papers using the web template and then create new observation for each species using the same Reference?
<img width="1680" alt="Screen Shot 2020-07-23 at 4 11 15 PM" src="https://user-images.githubusercontent.com/4634830/88328821-63202800-ccff-11ea-992f-1d7cf1b32e39.png">
<img width="1680" alt="Screen Shot 2020-07-23 at 4 12 51 PM" src="https://user-images.githubusercontent.com/4634830/88328843-6c10f980-ccff-11ea-8180-ebf6baae4eef.png">
<img width="1680" alt="Screen Shot 2020-07-23 at 4 11 51 PM" src="https://user-images.githubusercontent.com/4634830/88328877-77fcbb80-ccff-11ea-8b6c-236af051f8e8.png">

**Comment by coffeejunk** [comment]
This more of a side-note: We now have the concept of a "Species Group," which is essentially a virtual envelope that links several species together. We use this, for example, [here](https://www.sharkipedia.org/trends/1834), where the data for the trend is related to both Alopias superciliosus as well as Alopias vulpinus. 
I'm not entirely sure that this will be useful for traits since here, the data is (correct me if I'm wrong) not grouped for several species together, but one paper references multiple observations for different species (i.e. a single datum points to a single species). Then again the paper as a whole references a group of species. What are your thoughts on this?

Regarding the issue in general, I can change the species relationship to be on the measurement level instead of the observation level. However, we'll either have to re-import the current trait data (I don't know how much the actual data in the database has deviated from the original excel sheet by now and if this would still be feasible) or someone has to manually fix the incorrect ones that we currently have in the database.

**Comment by sebpardo** [comment]
Hi @coffeejunk, personally I don't think the species groups would be as useful for the traits database given what you pointed out; we don't really get trait measurements that encompass more than one species. This could change though, particularly if a species is split in the future.

If I understand this bug correctly, it seems that the issue is not whether the species relationship is on the measurement level or the observation level, but that the db structure is not requiring observations to be of a single species. We can keep the species relationship as is at the observation level, but when there's an import where there's one reference with multiple species, the import tool should group each species in that reference, and all the measurements for it, as a separate observation.

Structurally I'm not sure what would be the best way to do this, but I thought I'd share my two cents.

**Comment by creeas** [comment]
Hey @coffeejunk I just wanted to reopen this issue. I think your earlier suggestion of moving the species to the measurement level would be the easiest way to go, unless you can think of a way to incorporate Seb's suggestion of the importer IDing both species. I think the opposite of what Seb suggested is true though and the db is currently requiring each observation to be of a single species. It may be easier from your end to simply move species to the measurement level.

As for correcting the database currently I have maintained all of the original template upload files and can reimport them. We have been continuing to compile data but holding off on importing until this gets resolved. Let me know if I can help in anyway and can run tests on any isolated deployments before merging. Thanks!

**Comment by coffeejunk** [comment]
Hey @creeas I'll be looking into this in the coming days. In the meantime, could you email me the latest version of the excel sheet so I can make sure the imported handles it correctly?

**Comment by creeas** [comment]
Thanks a ton @coffeejunk Yes I will e-mail the updated template to you ASAP!
