### ISSUE TITLE
Add automatic checks of import files before being available to curators

### ISSUE THREAD

**Issue by sebpardo** [sharkipedia/sharkipedia#17]
WORK IN PROGRESS

- [x] columns that need to have data in them: resource_name, species_name, location_name, sex, trait_class, trait_name, standard_name, value
- [x] resource_name from existing list of resources (if no new resource information is specified)
- [x] species_name from existing list of species
- [x] sex from options (male, female, unspecified, pooled/combined)
- [x] trait_class from existing trait_classes
- [x] trait_name from existing trait_names
- [x] standard_name for list of standard_names
- [x] doi regex: `^10.\d{4,9}/[-._;()/:A-Z0-9]+$` or `\b(10[.][0-9]{4,}(?:[.][0-9]+)*/(?:(?!["&\'<>])\S)+)\b` (see https://www.regextester.com/96937 and https://www.crossref.org/blog/dois-and-matching-regular-expressions/)

**Comment by hkindsvater** [comment]
To an unfamiliar user, the resources/reference link, and where to look for resources isn't clear. This should be in the FAQ

**Comment by hkindsvater** [comment]
discussion with @creeas we need to make these less restrictive: the uploading process has to be simple for users if we want buy-in and to prevent frustration. Insisting that species name or resource name have a match is too onerous. A lot of these will be caught in the template and are not needed in my opinion.

**Comment by sebpardo** [comment]
@hkindsvater I disagree, these checks are definitely needed. We pitched high data quality as being a key difference between Shark Traits and Fishbase. 

Data quality, together with the ability to link every trait value with its respective resource, are the two things we cannot get lax about. Data entered from the first large imports definitely need to match existing resource_names, or alternatively, users need to provide the complete resource information. We need to have all values matching with a valid resource. This has been **the** key feature of Shark Traits from the very beginning.

We also need to minimize the time spent curating the database and make sure that the data being entered require as little additional work as possible. Any automatic checks that can be done before imports are staged for curation, should be done. It will save lots of headaches down the line, and they require relatively little coding work to be implemented.

With regards to prevent frustration from users, if they use the template properly, then these checks should be frustration-free and not throw any errors. But they need to be picked up on as early as possible if we don't want to end up with a mess of a database that editors will spend weeks trying to fix.

**Comment by coffeejunk** [comment]
DOI validation is implemented and deployed: 

Trends:
<img width="1207" alt="Screenshot 2019-04-24 21 27 05" src="https://user-images.githubusercontent.com/205556/56703621-bb6d1200-66d7-11e9-9640-c06afdfed7eb.png">

Traits:
<img width="1250" alt="Screenshot 2019-04-24 21 28 16" src="https://user-images.githubusercontent.com/205556/56703667-f53e1880-66d7-11e9-8164-af6327f12ec9.png">
<img width="1273" alt="Screenshot 2019-04-24 21 28 22" src="https://user-images.githubusercontent.com/205556/56703668-f53e1880-66d7-11e9-8f14-6ca8b94a6dbb.png">
<img width="1243" alt="Screenshot 2019-04-24 21 28 37" src="https://user-images.githubusercontent.com/205556/56703669-f53e1880-66d7-11e9-9ced-872118a295e2.png">

please let me know if you want the messages to say something else

**Comment by coffeejunk** [comment]
> [ ] resource_name from existing list of resources

@sebpardo @hkindsvater I was operating with the understanding that an import would either reference an existing resource or create a new one. Is that not the case?

**Comment by creeas** [comment]
@coffeejunk yes any uploaded data needs to reference an existing resource or create a unique ID and provide a valid DOI. That example looks great, and I like how the log refers to specific rows requiring attention.

@sebpardo: @hkindsvater isn't suggesting that we get lax about the quality of the data, and there will not be any data imported into the database that does not meet the criteria set forth by the QA/QC checks in place for curators. I think we need to balance the ease of users with the burden on curators. Remember a big issue that Josh Madin pointed out with CoralTraits was getting users to continue populating and uploading data following the initial launch. There will always be checks in place, the question is whether we implement them at the user upload stage or the importation following curation stage. But making the rules very restrictive for uploaders may turn users off, and the role of curator will come with added responsibilities. One thing we have not yet laid out is the protocol for data curation and this could be designed to take care of some of these issues. For some columns such as trait_class, method, model_name restrictive rules may be easy to implement, and hopefully @coffeejunk can code these so that they will also be specifically referred to in the upload log as in the example above. But resource_id and species_id may require some tweaking. For example for data entered for a resource_id not included in the shark-references database how will uploaders be able to include this data? Currently the template protocol has them create a unique ID according to authorYEAR format, but with a restrictive rule for uploading this won't pass a check and they will need to first contact an administrator and have that reference included in the database. We need to have a protocol and check in place that allows them to create a unique resource_ID, denote that it is a new reference, and provide information so the curator can include this in the reference list.

Another case will be for newly described species that are not in our taxonomy but are valid. If we create a restrictive rule that they must be on our taxonomy then users cannot upload this data. I think we can get around this by adding a 'recently described' designation to the species list and template that will allow users to enter and upload this data, but it will be clearly denoted for curators that this data needs to be hidden. A curator will be required to ensure that this data is embargoed prior to any official taxonomic publication.

@coffeejunk will a curator have the ability to manually edit a cell of a user updated dataset (e.g. hidden) prior to importing? Or will the curator need to request this change from the user?

**Comment by coffeejunk** [comment]
> @coffeejunk will a curator have the ability to manually edit a cell of a user updated dataset (e.g. hidden) prior to importing? Or will the curator need to request this change from the user?

@creeas right now the user needs to re-upload a changed dataset and I intend to keep it that way, at least for now. It's technically possible to allow a user to edit the spreadsheet but there are a number of technical implications that are unclear to me at the moment..

**Comment by sebpardo** [comment]
> @sebpardo @hkindsvater I was operating with the understanding that an import would either reference an existing resource or create a new one. Is that not the case?

You are correct Max. I think there's still needs to be a check in place that, if no new resource information is specified, then the resource_name needs to be checked with the list. Otherwise we risk having resource-less traits from the very beginning.

**Comment by coffeejunk** [comment]
@sebpardo I've implemented the requested import validations see https://shark-t-staging.herokuapp.com/imports/13 as an example. Please have a look and let me know what you think.

**Comment by sebpardo** [comment]
This looks great! @creeas you should have a look through as well.

I can see that some of the validations are too restrictive, so would it be possible to add some conditional checks? For example, if `trait_class == "Relationships" or "Growth"`, then do not require a `standard_name` to be specified (although technically, the value of the coefficients (e.g. a, b, k, Linf) are mean values and ideally should ideally be specified as such).

**Comment by creeas** [comment]
Thanks for getting this together @coffeejunk. I'll have a go at uploading data with the new uploading restrictions and see how they go. We need to be careful that the restrictions do not exclude users from uploading useful data, and thus need to be aware of legitimate exceptions to the rules. This was why we had the discussion earlier. @sebpardo pointed out a useful example above, but I am still concerned about the taxonomy. I am trying to get a list of all the species that we can expect to be added to the IUCN taxonomy in the coming year. For now I think we should use our taxonomic list with an additional 'Newly described species' selection. I will add the protocol for this to the FAQs page.

**Comment by sebpardo** [comment]
I think @creeas has a much better idea of how to deal with taxonomic updates than I do, so the `species` requirement might be better to be more flexible; I'll defer to @creeas on this one.
