### ISSUE TITLE
Move Date field on new trait observation form

### ISSUE THREAD

**Issue by hkindsvater** [sharkipedia/sharkipedia#57]
Date field refers to date collected, not date of measurement entry (which we need to log automatically please). so each new measurement should have a date field underneath the heading. 
<img width="1466" alt="Screen Shot 2019-10-04 at 1 56 25 PM" src="https://user-images.githubusercontent.com/8378070/66228985-d001fd00-e6ae-11e9-85c5-5ea13d6ea800.png">

**Comment by creeas** [comment]
Also the user information could be automatically filled, as users should be required to be logged in to enter data.

**Comment by hkindsvater** [comment]
This comment might apply to depth field too - does each measurement have its own depth?

**Comment by creeas** [comment]
I think the depth could remain in the observation level. I can't think of any studies reporting traits from different depths.

**Comment by coffeejunk** [comment]
> Date field refers to date collected, not date of measurement entry (which we need to log automatically please). so each new measurement should have a date field underneath the heading.

Oh. This is a bug then. We currently have the date attached to the observation not the measurement. Will fix.

> Also the user information could be automatically filled, as users should be required to be logged in to enter data.

Hm good point. The contributor id stems from the spreadsheet which has that column but this isn't really necessary for the form since the contributor is the user.

> This comment might apply to depth field too - does each measurement have its own depth?

We originally had the depth on the measurement level and then moved it to the observation level. I can reverse this if necessary.
